compile: main.c Compartimento/Compartimento.c Mineral/Mineral.c ListaMinerais/ListaMinerais.c RochaMineral/RochaMineral.c
	gcc -o main main.c Compartimento/Compartimento.c Mineral/Mineral.c ListaMinerais/ListaMinerais.c RochaMineral/RochaMineral.c
run: 
	./main.exe
